CREATE DATABASE CJOBDD2;
USE CJOBDD2;

CREATE TABLE CUSTOMER (
  CUS_CODE INT NOT NULL,
  CUS_LNAME VARCHAR(45) NOT NULL,
  CUS_FNAME VARCHAR(45) NOT NULL,
  CUS_INITIAL CHAR(1) NULL,
  CUS_AREACODE CHAR(3) NOT NULL,
  CUS_PHONE CHAR(8) NOT NULL,
  CUS_BALANCE DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (CUS_CODE)
);

CREATE TABLE VENDOR (
  V_CODE INT NOT NULL,
  V_NAME VARCHAR(100) NOT NULL,
  V_CONTACT VARCHAR(50) NOT NULL,
  V_AREACODE CHAR(3) NOT NULL,
  V_PHONE CHAR(8) NOT NULL,
  V_STATE CHAR(2) NOT NULL,
  V_ORDER CHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (V_CODE)
);

CREATE TABLE PRODUCT (
  P_CODE VARCHAR(15) NOT NULL,
  V_CODE INT NULL,
  P_DESCRIPT VARCHAR(100) NOT NULL,
  P_INDATE DATE NOT NULL,
  P_QOH INT NOT NULL DEFAULT 0,
  P_MIN INT NOT NULL,
  P_PRICE DECIMAL(10,2) NOT NULL,
  P_DISCOUNT DECIMAL(4,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (P_CODE),
  CONSTRAINT fk_PRODUCT_VENDOR
    FOREIGN KEY (V_CODE)
    REFERENCES VENDOR (V_CODE)
);

CREATE TABLE INVOICE (
  INV_NUMBER INT NOT NULL,
  CUS_CODE INT NOT NULL,
  INV_DATE DATE NOT NULL,
  PRIMARY KEY (INV_NUMBER),
  CONSTRAINT fk_INVOICE_CUSTOMER
    FOREIGN KEY (CUS_CODE)
    REFERENCES CUSTOMER (CUS_CODE)
);

CREATE TABLE LINE (
  LINE_NUMBER INT NOT NULL,
  INV_NUMBER INT NOT NULL,
  P_CODE VARCHAR(15) NOT NULL,
  LINE_UNITS INT NOT NULL DEFAULT 1,
  LINE_PRICE DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (LINE_NUMBER, INV_NUMBER),
  CONSTRAINT fk_LINE_PRODUCT
    FOREIGN KEY (P_CODE)
    REFERENCES PRODUCT (P_CODE),
  CONSTRAINT fk_LINE_INVOICE
    FOREIGN KEY (INV_NUMBER)
    REFERENCES INVOICE (INV_NUMBER)
);